### ISSUE TITLE
Phase 01 - Development TODO - Discovery and exchange messages between nodes

### ISSUE THREAD

**Issue by brustulim** [brustulim/p2pwire#5]
- [X] Create an initial app with browserify to open in browser and do initial tests/study
- [X] Implement webtorrent, master address and peer discovery
- [X] Introduce ES6 + starndardjs + babelify + browserify
  - change the application to support ES6 and follow the standardJS rules/patterns
- [x] Introduce connections store - 
  - a mechanism to crud nodes, resources, and groups, with their relations 
- [x] Introduce store crud from club actions/events 
- [x] Introduce packet creation, send and receive
